/**
 * Business facts and interface strings (EN / FR) for VAHAI TAX.
 * Single source of truth for NAP data used in HTML, footer and JSON-LD.
 */
module.exports = {
  // Override with the SITE_URL environment variable at build time.
  // Project pages on GitHub Pages: https://<user>.github.io/<repo>
  // Custom domain:                 https://www.example.ca
  DEFAULT_SITE_URL: 'https://vahaitax.ca',

  BRAND: 'VAHAI TAX - Accountants and Consultants',
  BRAND_SHORT: 'VAHAI TAX',
  PRINCIPAL: 'Vasugi Selvaelango',

  ADDRESS: {
    street: '885 Progress Ave., Unit 102',
    city: 'Scarborough',
    region: 'ON',
    postal: 'M1H 3G3',
    country: 'CA',
  },

  PHONES: [
    { display: '416-439-2688', tel: '+14164392688' },
    { display: '647-221-6262', tel: '+16472216262' },
  ],

  // The brief printed this address as "vahai tax@gmail.com" (contains a space,
  // which is not a valid email). Confirm the correct mailbox here.
  EMAIL: 'vahaitax@gmail.com',

  MAPS_URL:
    'https://www.google.com/maps/search/?api=1&query=' +
    encodeURIComponent('885 Progress Ave Unit 102, Scarborough, ON M1H 3G3'),

  CRA_HOME: {
    en: 'https://www.canada.ca/en/revenue-agency.html',
    fr: 'https://www.canada.ca/fr/agence-revenu.html',
  },

  // CRA direct-dial numbers
  CRA_NUMBERS: {
    personal: [
      { key: 'income', display: '1-800-959-8281', tel: '+18009598281' },
      { key: 'ccb', display: '1-800-387-1193', tel: '+18003871193' },
      { key: 'payment', display: '1-888-863-8657', tel: '+18888638657' },
    ],
    business: [
      { key: 'general', display: '1-800-959-5525', tel: '+18009595525' },
      { key: 'hst', display: '1-800-959-5525', tel: '+18009595525' },
      { key: 'corp', display: '1-866-333-5556', tel: '+18663335556' },
    ],
  },

  UI: {
    en: {
      htmlLang: 'en-CA',
      ogLocale: 'en_CA',
      skip: 'Skip to main content',
      brand_aria: 'VAHAI TAX - Accountants and Consultants, home',
      brand_sub: 'Accountants & Consultants',
      nav_primary: 'Primary',
      nav_mobile: 'Mobile',
      language: 'Language',
      menu_open: 'Open menu',
      menu_close: 'Close menu',
      call_aria: 'Call',
      call_now: 'Call',
      home: 'Home',
      overview: 'Overview',
      breadcrumb: 'Breadcrumb',
      learn_more: 'Learn more',
      view_all: 'View all',
      related: 'Related Services',
      related_resources: 'More Resources',
      consult: 'Book a Consultation',
      contact_us: 'Contact Us',
      speak_with: 'Speak with Vasugi Selvaelango',
      speak_with_p: 'Call or email to arrange a consultation at our Scarborough office.',
      credential: 'Over 20 Years of Experience in Income Tax and Accounting',
      principal_title: 'Tax Consultant',
      email_label: 'Email',
      phone_label: 'Phone',
      visit_label: 'Visit',
      directions: 'Get directions',
      services_h: 'Our Services',
      services_p: 'Three practice areas, one office. Select a service to see what is included.',
      quick_h: 'Tax Answers at a Glance',
      why_h: 'Why Clients Choose VAHAI TAX',
      cra_h: 'CRA Important Numbers',
      cra_p: 'Direct-dial numbers for the Canada Revenue Agency.',
      cra_personal: 'Personal',
      cra_business: 'Business',
      cra_labels: {
        income: 'Individual Income Tax',
        ccb: 'Canada Child Benefit',
        payment: 'Payment Arrangements',
        general: 'General Inquiries',
        hst: 'HST/GST/Payroll',
        corp: 'Corporations Canada',
      },
      cta_h: 'Ready to simplify your taxes?',
      cta_p: 'Speak with an experienced tax consultant about your personal, business or corporate filing needs.',
      principal_card_h: 'Principal',
      meet: 'Meet Vasugi Selvaelango',
      visit_h: 'Visit Our Office',
      call_h: 'Call Us',
      email_h: 'Email Us',
      footer_company: 'Company',
      disclaimer:
        'Information on this website is general in nature and is not tax, legal or accounting advice for your situation. Tax rules change, so please contact us before acting on it.',
      rights: 'All rights reserved.',
      nf_title: 'Page not found',
      nf_h1: 'We could not find that page',
      nf_p: 'The page may have moved. Use the links below or call us at',
      nf_fr: 'Page introuvable. Retournez à la version française de notre site.',
    },
    fr: {
      htmlLang: 'fr-CA',
      ogLocale: 'fr_CA',
      skip: 'Passer au contenu principal',
      brand_aria: 'VAHAI TAX - Comptables et consultants, accueil',
      brand_sub: 'Comptables et consultants',
      nav_primary: 'Principale',
      nav_mobile: 'Mobile',
      language: 'Langue',
      menu_open: 'Ouvrir le menu',
      menu_close: 'Fermer le menu',
      call_aria: 'Appeler',
      call_now: 'Appeler',
      home: 'Accueil',
      overview: 'Aperçu',
      breadcrumb: "Fil d'Ariane",
      learn_more: 'En savoir plus',
      view_all: 'Voir tout',
      related: 'Services connexes',
      related_resources: 'Autres ressources',
      consult: 'Prendre rendez-vous',
      contact_us: 'Nous joindre',
      speak_with: 'Parlez à Vasugi Selvaelango',
      speak_with_p: 'Appelez ou écrivez-nous pour fixer un rendez-vous à notre bureau de Scarborough.',
      credential: "Plus de 20 ans d'expérience en impôt et en comptabilité",
      principal_title: 'Consultante fiscale',
      email_label: 'Courriel',
      phone_label: 'Téléphone',
      visit_label: 'Adresse',
      directions: "Obtenir l'itinéraire",
      services_h: 'Nos services',
      services_p: 'Trois domaines de pratique, un seul bureau. Choisissez un service pour voir ce qu’il comprend.',
      quick_h: "L'essentiel de la fiscalité en bref",
      why_h: 'Pourquoi les clients choisissent VAHAI TAX',
      cra_h: "Numéros importants de l'ARC",
      cra_p: "Numéros directs de l'Agence du revenu du Canada.",
      cra_personal: 'Particuliers',
      cra_business: 'Entreprises',
      cra_labels: {
        income: 'Impôt des particuliers',
        ccb: "Allocation canadienne pour enfants",
        payment: 'Ententes de paiement',
        general: 'Renseignements généraux',
        hst: 'TPS/TVH et retenues sur la paie',
        corp: 'Corporations Canada',
      },
      cta_h: 'Prêt à simplifier vos impôts?',
      cta_p: "Parlez à une consultante fiscale expérimentée de vos besoins personnels, d'entreprise ou de société.",
      principal_card_h: 'Dirigeante',
      meet: 'Faire connaissance avec Vasugi Selvaelango',
      visit_h: 'Visitez notre bureau',
      call_h: 'Appelez-nous',
      email_h: 'Écrivez-nous',
      footer_company: 'Entreprise',
      disclaimer:
        "L'information de ce site est de nature générale et ne constitue pas un avis fiscal, juridique ou comptable adapté à votre situation. Les règles fiscales changent; communiquez avec nous avant d'agir.",
      rights: 'Tous droits réservés.',
      nf_title: 'Page introuvable',
      nf_h1: 'Nous ne trouvons pas cette page',
      nf_p: 'La page a peut-être été déplacée. Utilisez les liens ci-dessous ou appelez-nous au',
      nf_fr: '',
    },
  },
};
